### ISSUE TITLE
shortcut keys not working on linux build

### ISSUE THREAD

**Issue by muralikodali** [ImXico/Moonpad#4]
I have built linux version of Moonpad.
shortcut keys are not working. 

error output as follows :    

> [469212:0824/142343.165002:ERROR:buffer_manager.cc(488)] [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : glBufferData: <- error from previous GL command

**Comment by ImXico** [comment]
Hey, thank you for trying it out on Linux!

For the shortcut keys the code is currently using the [event#metaKey](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/metaKey), which I thought would map to `Ctrl` on Windows/Linux, but apparently that is not the case. I'll try to commit an update to that later. Thank you.

**Comment by ImXico** [comment]
@muralikodali This should be fixed now. If you get around to trying it out again, could you please confirm? Thank you. 🙂

**Comment by muralikodali** [comment]
Thanks. app is now running with shortcuts.
expecting to see some improvements like theme,font size and go to line number etc.

yarn install giving some warnings as shown below :  

```
1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@2.0.7: The platform "linux" is incompatible with this module.
info "fsevents@2.0.7" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.13: The platform "linux" is incompatible with this module.
info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@2.1.3: The platform "linux" is incompatible with this module.
info "fsevents@2.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning "react-scripts > @typescript-eslint/eslint-plugin > tsutils@3.17.1" has unmet peer dependency "typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta".
[4/4] Building fresh packages...

```

**Comment by ImXico** [comment]
Themes is still WIP (in fact a lot of the code is still there). As for font size/line numbers, I agree those'd be nice improvements. I'll try to squeeze in the implementation whenever I can, but probably won't be in the near future. Will close this issue and add those ideas to the backlog. Wasn't aware of the yarn warnings — sucks not having a Linux environment to try these things out.

Thanks for trying out the app and thanks for the input!
